/**
 * The architects, printed as the city map's walker icons (lib/walker-cast.ts):
 * each at three points of a stride — legs together, half apart, apart — and
 * facing either way, since the map engine can't turn an icon round.
 *
 *   npx tsx scripts/iso/walker-icons.ts  → assets/walkers/*.png, components/walker-icons.generated.ts
 */
import fs from "node:fs";
import { createCanvas, Path2D } from "@napi-rs/canvas";

import { BODY, CAST, HEAD, HEAD_INK, LEGS, WALKERS } from "../../lib/walker-cast";

const DIR = "assets/walkers";
const MODULE = "components/walker-icons.generated.ts";
/** Pixels to a unit of the figure's box. */
const PX = 4;
/** The box, with room for the legs' swing: x from -1 to 15, y from -1 down to the feet at 34. */
const [X0, Y0, W, H] = [-1, -1, 16, 35];
/** The keyline round coat and head, in the figure's units. */
const KEYLINE = 0.55;
/** The stride: how far the legs are apart, degrees, and how far the walker rises with it. */
export const STRIDE = [
  { swing: 0, rise: 0 },
  { swing: LEGS.swing * 0.55, rise: 0.5 },
  { swing: LEGS.swing, rise: 0.9 },
];

fs.mkdirSync(DIR, { recursive: true });
for (const f of fs.readdirSync(DIR)) if (f.endsWith(".png")) fs.unlinkSync(`${DIR}/${f}`);

const names: string[] = [];
for (const key of WALKERS) {
  const fig = CAST[key];
  STRIDE.forEach(({ swing, rise }, s) => {
    for (const face of ["r", "l"] as const) {
      const c = createCanvas(W * PX, H * PX);
      const g = c.getContext("2d");
      g.scale(PX, PX);
      g.translate(-X0, -Y0 - rise);
      if (face === "l") {
        g.translate(7, 0);
        g.scale(-1, 1);
        g.translate(-7, 0);
      }
      LEGS.left.forEach((left, i) => {
        g.save();
        g.translate(left + LEGS.width / 2, LEGS.top);
        g.rotate((((i === 0 ? 1 : -1) * swing) * Math.PI) / 180);
        g.fillStyle = LEGS.ink;
        g.fillRect(-LEGS.width / 2, 0, LEGS.width, LEGS.height);
        g.restore();
      });
      const fill = (d: string, ink: string) => {
        g.fillStyle = ink;
        g.fill(new Path2D(d));
      };
      // A fine charcoal keyline round the coat and head, so a paper coat
      // still reads on the map's paper streets.
      g.strokeStyle = LEGS.ink;
      g.lineWidth = KEYLINE * 2;
      g.lineJoin = "round";
      for (const d of [fig.skirt ? BODY.skirt : BODY.coat, HEAD]) g.stroke(new Path2D(d));
      fill(fig.skirt ? BODY.skirt : BODY.coat, fig.coat);
      fill(HEAD, fig.head ?? HEAD_INK);
      for (const m of fig.marks) fill(m.d, m.fill);
      const name = `${key}-${s}${face}`;
      fs.writeFileSync(`${DIR}/${name}.png`, c.toBuffer("image/png"));
      names.push(name);
    }
  });
}

fs.writeFileSync(
  MODULE,
  `// AUTO-GENERATED by scripts/iso/walker-icons.ts — do not edit.\n` +
    `/** The walkers' icons: "<architect>-<stride 0–2><r|l>". */\n` +
    `export const WALKER_ICONS: Record<string, number> = {\n` +
    names.map((n) => `  "${n}": require("../assets/walkers/${n}.png"),`).join("\n") +
    `\n};\n` +
    `/** An icon's size, in the figure's units (its box is 14 × 34, feet at the bottom), and pixels to the unit. */\n` +
    `export const WALKER_ICON = ${JSON.stringify({ width: W, height: H, px: PX, strides: STRIDE.length })};\n`,
);
console.log(`${names.length} icons → ${DIR}; ${MODULE}`);
