// Generated by scripts/logo-streets.py from assets/images/logo-on-blue.png — don't edit by hand.
//
// The streets cut into the Campanile device's slab, in the image's own
// pixels (648 × 737). `edge` marks the street ends at the slab's rim, where
// walkers come and go; `tower` is the region the tower hides (its shaft, down
// to the front of its foot), which assets/images/logo-tower.png prints over.
export const LOGO_STREETS = {
  size: [648, 737] as const,
  nodes: [[265.7, 354.8], [325.5, 389.8], [379.6, 421.5], [432.7, 452.6], [483.4, 482.3], [535.8, 513.0], [580.5, 539.2], [209.9, 387.2], [269.7, 422.3], [323.8, 453.9], [376.8, 485.0], [427.6, 514.7], [479.9, 545.4], [524.7, 571.6], [158.6, 417.0], [218.4, 452.0], [272.5, 483.7], [107.3, 446.8], [167.1, 481.8], [221.2, 513.5], [274.3, 544.6], [325.0, 574.3], [377.4, 605.0], [422.2, 631.2], [55.7, 476.8], [115.5, 511.8], [169.6, 543.5], [222.6, 574.6], [273.4, 604.3], [325.7, 635.0], [370.5, 661.2], [385.0, 355.3], [67.8, 539.5], [439.1, 387.0], [121.9, 571.2], [492.1, 418.1], [542.8, 447.8], [376.3, 544.5], [225.7, 632.0], [595.2, 478.4], [428.7, 575.2], [278.0, 662.7]] as [number, number][],
  edge: [true, false, false, false, false, false, true, true, false, false, false, false, false, true, true, false, false, true, false, false, false, false, false, true, true, false, false, false, false, false, true, true, true, true, true, true, true, false, true, true, false, true],
  links: [[0, 1], [1, 2], [2, 3], [3, 4], [4, 5], [5, 6], [7, 8], [8, 9], [9, 10], [10, 11], [11, 12], [12, 13], [14, 15], [15, 16], [17, 18], [18, 19], [19, 20], [20, 21], [21, 22], [22, 23], [24, 25], [25, 26], [26, 27], [27, 28], [28, 29], [29, 30], [31, 1], [1, 8], [8, 15], [15, 18], [18, 25], [25, 32], [33, 2], [2, 9], [9, 16], [16, 19], [19, 26], [26, 34], [35, 3], [3, 10], [36, 4], [4, 11], [11, 37], [37, 21], [21, 28], [28, 38], [39, 5], [5, 12], [12, 40], [40, 22], [22, 29], [29, 41]] as [number, number][],
  tower: { left: 249, right: 400, foot: [[250.0, 518.0], [326.0, 564.0], [400.0, 520.0]] as [number, number][] },
};
