/**
 * GENERATED by scripts/build_glyphs.mjs — do not edit by hand.
 *
 * Static requires for every offline glyph PBF so Metro bundles them as
 * assets. At runtime MapLibreView copies them into
 * <cacheDirectory>/map-glyphs/<fontstack>/<range>.pbf and points the
 * style's `glyphs` URL there for full offline text rendering.
 */
export const GLYPH_ASSETS: Record<string, number> = {
  "Noto Sans Bold/0-255": require("../assets/map/glyphs/Noto Sans Bold/0-255.pbf") as number,
  "Noto Sans Bold/256-511": require("../assets/map/glyphs/Noto Sans Bold/256-511.pbf") as number,
  "Noto Sans Bold/768-1023": require("../assets/map/glyphs/Noto Sans Bold/768-1023.pbf") as number,
  "Noto Sans Regular/0-255": require("../assets/map/glyphs/Noto Sans Regular/0-255.pbf") as number,
  "Noto Sans Regular/256-511": require("../assets/map/glyphs/Noto Sans Regular/256-511.pbf") as number,
  "Noto Sans Regular/768-1023": require("../assets/map/glyphs/Noto Sans Regular/768-1023.pbf") as number,
  "Noto Serif Bold/0-255": require("../assets/map/glyphs/Noto Serif Bold/0-255.pbf") as number,
  "Noto Serif Bold/256-511": require("../assets/map/glyphs/Noto Serif Bold/256-511.pbf") as number,
  "Noto Serif Bold/768-1023": require("../assets/map/glyphs/Noto Serif Bold/768-1023.pbf") as number,
  "Noto Serif Regular/0-255": require("../assets/map/glyphs/Noto Serif Regular/0-255.pbf") as number,
  "Noto Serif Regular/256-511": require("../assets/map/glyphs/Noto Serif Regular/256-511.pbf") as number,
  "Noto Serif Regular/768-1023": require("../assets/map/glyphs/Noto Serif Regular/768-1023.pbf") as number,
};
