// AUTO-GENERATED by scripts/bake_tiles.mjs — do not edit.
/** Berkeley core (sharp, fully themed). */
export const CORE_BBOX = { minLat: 37.85, maxLat: 37.9, minLon: -122.32, maxLon: -122.24 } as const;
/** Themed-tile coverage: inside this rect tiles are baked; outside it the map fades to the theme background. */
export const MID_RECT = { minLat: 37.78500, maxLat: 37.96500, minLon: -122.41000, maxLon: -122.15000 } as const;
export const TILES_VERSION = 2;
